<style>
  @import "../../app.css";
</style>

<script>
  import { goto } from "$app/navigation";
  import { addUser } from './storage.js';
  export async function handleCancel() {
    goto("../login");
  }

  export async function handleCreateAccount() {
    const firstnameInput = document.getElementById("firstname-input");
    const lastnameInput = document.getElementById("lastname-input");
    const emailInput = document.getElementById("email-input");
    const contactInput = document.getElementById("contact-input");
    const passwordInput = document.getElementById("password-input");

    const first_name = firstnameInput.value.trim();
    const last_name = lastnameInput.value.trim();
    const email = emailInput.value.trim();
    const phone = contactInput.value.trim();
    const password = passwordInput.value.trim();

    // Validate input fields here (you can add more validation if needed)

    // Example validation: Check if fields are not empty
    if (first_name === "" || last_name === "" || email === "" || phone === "" || password === "") {
      alert("Please fill in all the fields.");
      return;
    }

    // Validate input fields here
    const namePattern = /^[A-Za-z]+$/;
    const emailPattern = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    const phonePattern = /^\d{8}$/;
    const passwordPattern = /^\d{5}$/;

    if (!namePattern.test(first_name)) {
      alert("Invalid first name. Please use letters only.");
      return;
    }

    if (!namePattern.test(last_name)) {
      alert("Invalid last name. Please use letters only.");
      return;
    }

    if (!emailPattern.test(email)) {
      alert("Invalid email format. Please use the format 'example@example.com'.");
      return;
    }

    if (!phonePattern.test(phone)) {
      alert("Invalid phone number. Please enter exactly 8 digits.");
      return;
    }

    if (!passwordPattern.test(password)) {
      alert("Invalid password. Please enter exactly 5 digits.");
      return;
    }

    try {
      const response = await fetch("../api/bankapp/adduser", {
        method: "POST",
        body: JSON.stringify({
          first_name,
          last_name,
          email,
          phone,
          password,
		      points: 0, // Points are set to 0
          notify_phone: true, 
          notify_email: true, 
		  // source_member_id generated by api
        }),
        headers: {
          "Content-Type": "application/json",
        },
      });

      if (response.ok) {
        addUser({
          first_name,
          last_name,
          email,
          phone,
          password,
          points: 0,
          notify_phone: true,
          notify_email: true,
        });
        alert("Account created successfully!");
        // Redirect the user to the login page after successful account creation
        goto("/login");
      } else {
        // Handle errors and show an appropriate error message
        const errorMessage = await response.text();
        alert(`Error: ${errorMessage}`);
      }
    } catch (error) {
      console.log(error);
    }
  }
</script>

<div class="hero min-h-screen bg-base-200">
  <div class="hero-content text-center">
    <div class="max-w-md">
      <h1 class="text-4xl font-bold py-5">Sign Up</h1>
      <table>
        <tr>
          <td><p class="py-5 pr-2 font-semibold">First name:</p><br></td>
          <td><input id="firstname-input" class="input input-bordered" placeholder="First name" data-testid="First name" /><p class="text-sm" data-testid="firstname-error">(Contains letters only)</p></td>
        </tr>
        <tr>
          <td><p class="py-5 pr-2 font-semibold">Last name:</p><br></td>
          <td><input id="lastname-input" class="input input-bordered" placeholder="Last name" data-testid="Last name"/><p class="text-sm" data-testid="lastname-error">(Contains letters only)</p></td>
        </tr>
        <tr>
          <td><p class="py-5 pr-2 font-semibold">Email (username):</p><br></td>
          <td><input id="email-input" class="input input-bordered" placeholder="Email" data-testid="Email"/><p class="text-sm">(Contains @ and .com)</p></td>
        </tr>
        <tr>
          <td><p class="py-5 pr-2 font-semibold">Contact:</p><br></td>
          <td><input id="contact-input" class="input input-bordered" placeholder="Contact" data-testid="Contact" /><p class="text-sm">(Contains exactly 8 digits)</p></td>
        </tr>
        <tr>
          <td><p class="py-5 pr-2 font-semibold">Password:</p><br></td>
          <td><input id="password-input" class="input input-bordered" type="password" placeholder="Password" data-testid="Password" /><p class="text-sm">(Contains exactly 5 digits)</p></td>
        </tr>
        <br>
      </table>
      <button class="btn" on:click={handleCancel}>Cancel</button>
      <button class="btn btn-primary" on:click={handleCreateAccount}>Create Account</button>
    </div>
  </div>
</div>
